export const store = {
  bbsStore: {
    postList: [
      {
        contents: [
          {
            no: 1,
            sj: "test3",
            regDt: "2022-06-23",
            regUserId: "user01",
            regUserNm: "가나다",
          },
          {
            no: 2,
            sj: "test1",
            regDt: "2022-06-24",
            regUserId: "user02",
            regUserNm: "나다가",
          },
          {
            no: 3,
            sj: "test2",
            regDt: "2022-06-24",
            regUserId: "user03",
            regUserNm: "다나가",
          },
          {
            no: 4,
            sj: "test2",
            regDt: "2022-06-24",
            regUserId: "user04",
            regUserNm: "다나가",
          },
          {
            no: 5,
            sj: "test2",
            regDt: "2022-06-26",
            regUserId: "user05",
            regUserNm: "다나가",
          },
          {
            no: 6,
            sj: "test2",
            regDt: "2022-06-26",
            regUserId: "user06",
            regUserNm: "다나가",
          },
          {
            no: 7,
            sj: "test2",
            regDt: "2022-06-26",
            regUserId: "user07",
            regUserNm: "다나가",
          },
          {
            no: 8,
            sj: "test2",
            regDt: "2022-06-26",
            regUserId: "user08",
            regUserNm: "다나가",
          },
          {
            no: 9,
            sj: "test2",
            regDt: "2022-06-26",
            regUserId: "user09",
            regUserNm: "다나가",
          },
          {
            no: 10,
            sj: "test2",
            regDt: "2022-06-26",
            regUserId: "user10",
            regUserNm: "다나가",
          },
        ],
        pagination: {
          totalElements: 20,
          pageSize: 10,
          pageNumber: 1,
        },
      },
      {
        contents: [
          {
            no: 11,
            sj: "test3",
            regDt: "2022-06-27",
            regUserId: "user11",
            regUserNm: "가나다",
          },
          {
            no: 12,
            sj: "test1",
            regDt: "2022-06-27",
            regUserId: "user12",
            regUserNm: "나다가",
          },
          {
            no: 13,
            sj: "test2",
            regDt: "2022-06-27",
            regUserId: "user13",
            regUserNm: "다나가",
          },
          {
            no: 14,
            sj: "test2",
            regDt: "2022-06-28",
            regUserId: "user14",
            regUserNm: "다나가",
          },
          {
            no: 15,
            sj: "test2",
            regDt: "2022-06-28",
            regUserId: "user15",
            regUserNm: "다나가",
          },
          {
            no: 16,
            sj: "test2",
            regDt: "2022-06-28",
            regUserId: "user16",
            regUserNm: "다나가",
          },
          {
            no: 17,
            sj: "test2",
            regDt: "2022-06-29",
            regUserId: "user17",
            regUserNm: "다나가",
          },
          {
            no: 18,
            sj: "test2",
            regDt: "2022-06-29",
            regUserId: "user03",
            regUserNm: "다나가",
          },
          {
            no: 19,
            sj: "test2",
            regDt: "2022-06-29",
            regUserId: "user19",
            regUserNm: "다나가",
          },
          {
            no: 20,
            sj: "test2",
            regDt: "2022-06-29",
            regUserId: "user20",
            regUserNm: "다나가",
          },
        ],
        pagination: {
          totalElements: 20,
          pageSize: 10,
          pageNumber: 2,
        },
      },
    ],
  },
};
